using System;
using System.Collections.Generic;
using SCI.Annotators.Original;

namespace SCI.Annotators
{
    class Lsl1Annotator : GameAnnotator
    {
        public override void Run()
        {
            RunEarly();
            GlobalRenamer.Run(Game, globals);
            ExportRenamer.Run(Game, exports);
            VerbAnnotator.Run(Game, verbs, ArrayToDictionary(0, inventoryVerbs));
            InventoryAnnotator.Run(Game, inventoryVerbs);
            FlagAnnotator.Run(Game, flags);
            RunLate();
        }

        protected override Dictionary<int, Original.Script[]> GameHeaders { get { return Lsl1Symbols.Headers; } }

        static IReadOnlyDictionary<int, string> globals = new Dictionary<int, string>
        {
            { 100, "gTheMusic" },
            { 101, "gHowFast" },
            { 102, "gTheMusic2" },
            { 103, "gCurReg" },
            { 104, "gNoCursor" },
            { 105, "gCursorType" },
            { 106, "gNumColors" },
            { 107, "gNumVoices" },
            { 108, "gRestartRoom" },
            { 109, "gDontSave" },
            { 110, "gSGrooper" },
            { 111, "gGameFlags" },
            { 118, "gEndGameFlags" },
            { 119, "gSaveCursorX" },
            { 120, "gSaveCursorY" },
            { 121, "gEHead" },
            { 122, "gFfRoom" },
            { 123, "gColBlack" },
            { 124, "gColGray1" },
            { 125, "gColGray2" },
            { 126, "gColGray3" },
            { 127, "gColGray4" },
            { 128, "gColGray5" },
            { 129, "gColWhite" },
            { 130, "gColDRed" },
            { 131, "gColLRed" },
            { 132, "gColVLRed" },
            { 133, "gColDYellow" },
            { 134, "gColYellow" },
            { 135, "gColLYellow" },
            { 136, "gColVDGreen" },
            { 137, "gColDGreen" },
            { 138, "gColLGreen" },
            { 139, "gColVLGreen" },
            { 140, "gColDBlue" },
            { 141, "gColBlue" },
            { 142, "gColLBlue" },
            { 143, "gColVLBlue" },
            { 144, "gColMagenta" },
            { 145, "gColLMagenta" },
            { 146, "gColCyan" },
            { 147, "gColLCyan" },
            { 148, "gColWindow" },
            { 151, "gActorX" },
            { 152, "gActorY" },
            { 153, "gLarryTime" },
            { 154, "gOldSysTime" },
            { 155, "gSpraySeconds" },
            { 157, "gSprayCounter" },
            { 158, "gLarryDollars" },
            { 159, "gDebugging" },
            { 161, "gFloorTo" },
            { 162, "gTvChannel" },
            { 164, "gCabFareMin" },
            { 165, "gDeathView" },
            { 166, "gDeathLoop" },
            { 167, "gTheMusic3" },
            { 168, "gDeathCycler" },
            { 169, "gLarrySpeed" },
            { 170, "gYourPart" },
            { 181, "gVideo" },
            { 211, "gYourClothing" },
            { 221, "gTheirName" },
            { 230, "gTheirPart" },
            { 240, "gTheirClothing" },
            { 250, "gObject" },
            { 260, "gRoom" },
            { 270, "gActivity" },
            { 290, "gLastByte" },
            { 292, "gGiantFont" },
            { 293, "gMonoFont" },
        };

        static IReadOnlyDictionary<Tuple<int, int>, string> exports = new Dictionary<Tuple<int, int>, string>()
        {
        };

        static IReadOnlyDictionary<int, string> verbs = new Dictionary<int, string>
        {
            { 1, "Walk" },
            { 2, "Look" },
            { 3, "Do" },
            { 5, "Talk" },
            { 10, "Zipper" },
            { 11, "Taste/Smell" },
            { 4, "Inventory" },
        };

        static string[] inventoryVerbs =
        {
            "wallet",
            "breathSpray",
            "watch",
            "apple",
            "ring",
            "whiskey",
            "remoteControl",
            "rose",
            "lubber",
            "candy",
            "discoPass",
            "pocketKnife",
            "wine",
            "magazine",
            "hammer",
            "pills",
            "ribbon",
            "graffiti",
        };

        static IReadOnlyDictionary<int, string> flags = new Dictionary<int, string>
        {
            { 0, "fAlleyWindowBroken" },
            { 1, "fBetInProgress" },
            { 2, "fComeOnIn" },
            { 3, "fDancedWithFawn" },
            { 4, "fDollFlies" },
            { 5, "fEgoUsingSpray" },
            { 6, "fEveHasApple" },
            { 7, "fEveKnowsLarry" },
            { 8, "fFailedCeremony" },
            { 9, "fFaithGone" },
            { 10, "fFawnAskedForBucks" },
            { 11, "fWhereDidSheGo" },
            { 12, "fFawnInRoom" },
            { 13, "fFawnIsGone" },
            { 14, "fFawnLeaves" },
            { 15, "fHasClap" },
            { 16, "fHookerWindowOpen" },
            { 17, "fJetsOff" },
            { 18, "fKnowsEvesName" },
            { 19, "fLarryPanting" },
            { 20, "fMouthSmellsBad" },
            { 21, "fNearPerson" },
            { 22, "fNoFawnInDisco" },
            { 23, "fOpenedDoor" },
            { 24, "fOrderedWine" },
            { 25, "fPentDoorsOpen" },
            { 26, "fPhoneRinging" },
            { 27, "fPimpStandingAside" },
            { 28, "fPimpWatchingTV" },
            { 29, "fPuncturedDoll" },
            { 30, "fReadTaxiSign" },
            { 31, "fReadyToDance" },
            { 32, "fReadyToMarry" },
            { 33, "fReturningCall" },
            { 34, "fRodeInCab" },
            { 35, "fScoredHooker" },
            { 36, "fSeenDeliveryBoyGag" },
            { 37, "fSmellsLikeDogPiss" },
            { 38, "fStiffedCabbie" },
            { 39, "fSurveyCalled" },
            { 40, "fToiletPaperOnShoe" },
            { 41, "fTurnedOnRadio" },
            { 42, "fTVOn" },
            { 43, "fWearingRubber" },
            { 44, "isVga" },
            { 45, "fLookedAtFawn" },
            { 46, "fCredits" },
            { 47, "nextFlag3" },
            { 48, "pAnsweredPhone" },
            { 49, "pAskedToSit" },
            { 50, "pBeenInPenthouse" },
            { 51, "pBoughtApple" },
            { 52, "pBoughtWhiskey" },
            { 53, "pCutRibbon" },
            { 54, "pDanceWithFawn" },
            { 55, "pDialedAjax" },
            { 56, "pDialedSierra" },
            { 57, "pDialedSurvey" },
            { 58, "pDidDoll" },
            { 59, "pGaveApple" },
            { 60, "pGaveFawnRose" },
            { 61, "pGaveFawnDiamond" },
            { 62, "pGaveFawnCandy" },
            { 63, "pGaveFawnBucks" },
            { 64, "pGavePills" },
            { 65, "pGotCandy" },
            { 66, "pGotDoll" },
            { 67, "pGotHammer" },
            { 68, "pGotKnife" },
            { 69, "pGotLubber" },
            { 70, "pGotMagazine" },
            { 71, "pGotMarried" },
            { 72, "pGotPass" },
            { 73, "pGotPills" },
            { 74, "pGotPimpToWatchTV" },
            { 75, "pGotRemote" },
            { 76, "pGotRibbon" },
            { 77, "pGotRing" },
            { 78, "pGotRose" },
            { 79, "pGotWine" },
            { 80, "pHeardLiquorStoreNumber" },
            { 81, "pInflatedDoll" },
            { 82, "pKnowsPassword" },
            { 83, "pLaidEve" },
            { 84, "pPoopedInCan" },
            { 85, "pReadMagazine" },
            { 86, "pReadTelephone" },
            { 87, "pRemovedRubber" },
            { 88, "pRodeInCab" },
            { 89, "pSatOnWhoopieCushion" },
            { 90, "pScoredHooker" },
            { 91, "pTalkedToFawn" },
            { 92, "pTalkedToFlasher" },
            { 93, "pTurnedOnTV" },
            { 94, "pTurnedOnRadio" },
            { 95, "pUsedPass" },
            { 96, "pWornRubber" },
            { 97, "fGotDizzy" },
            { 98, "fCaberetTgl" },
            { 99, "fBumTgl" },
            { 100, "fApplemanTgl" },
        };
    }
}
