using System;
using System.Collections.Generic;

namespace SCI.Annotators
{
    class Lsl7Annotator : GameAnnotator
    {
        public override void Run()
        {
            RunEarly();
            GlobalRenamer.Run(Game, globals);
            ExportRenamer.Run(Game, exports);
            VerbAnnotator.Run(Game, verbs);
            InventoryAnnotator.Run(Game, items);
            RunLate();

            Lsl7MessageAnnotator.Run(Game, MessageFinder);
        }

        static Dictionary<int, string> globals = new Dictionary<int, string>
        {
        };

        static IReadOnlyDictionary<Tuple<int, int>, string> exports = new Dictionary<Tuple<int, int>, string>()
        {
            { Tuple.Create(64000, 3), "WritePrefsFile" }, // me
            { Tuple.Create(64000, 4), "ReadPrefsFile" }, // me

            { Tuple.Create(64007, 2), "GetActorLoop" },

            { Tuple.Create(64032, 0), "TalkerName" },

            { Tuple.Create(64033, 0), "TextDialog" },
            { Tuple.Create(64033, 5), "YesNoDialog" },
            { Tuple.Create(64033, 7), "StackedButtonDialog" },
            { Tuple.Create(64033, 9), "DisplayMsgSequence" },

            { Tuple.Create(64038, 1), "AddDefaultVerbs" },

            { Tuple.Create(64040, 0), "InitializeTopics" }, // made up by me
            //{ Tuple.Create(64040, 1), "TestVerb" }, // made up by me, not sure. "Available"?
            { Tuple.Create(64040, 3), "UnmarkTopic" },
            { Tuple.Create(64040, 4), "RemoveTopic" },
            //{ Tuple.Create(64040, 5), "TestTopic" }, // made up by me, not sure. "Available"?

            // some from debug error messages, some not
            { Tuple.Create(64896, 0), "Face" },
            { Tuple.Create(64896, 3), "GetTextWidth" },
            { Tuple.Create(64896, 4), "GetTextHeight" },
            { Tuple.Create(64896, 5), "MakeMessageText" },
            { Tuple.Create(64896, 6), "IsStringObject" },
            { Tuple.Create(64896, 10), "GetNumMessages" },
            { Tuple.Create(64896, 11), "GetRandomNumber" },
            { Tuple.Create(64896, 14), "GetNumCases" },
            { Tuple.Create(64896, 16), "FadeTo" },
            { Tuple.Create(64896, 18), "CopyWinningWallpaper" },
            { Tuple.Create(64896, 23), "ShowEasterEgg" },

            { Tuple.Create(64928, 1), "MakeMessageSubTitle" }, // unused
        };

        // see PrintVerbs() below for how i generated this
        static Dictionary<int, string> verbs = new Dictionary<int, string>
        {
            { 1, "Look" },
            { 2, "Writing" },
            { 3, "Use" },
            { 4, "Talk" },
            { 5, "Feel" },
            { 6, "Touch" },
            { 7, "Lick" },
            { 8, "Take" },
            { 10, "Screw" },
            { 11, "Fart" },
            { 12, "Other..." },
            { 13, "Vice Grips" },
            { 14, "Needle" },
            { 15, "Captain Thygh" },
            { 16, "TMT Scorecard" },
            { 17, "Your Cabin Keycard" },
            { 18, "Dirty Pictures" },
            { 19, "Mucilage" },
            { 20, "Sticky Photograph" },
            { 21, "Photo ID" },
            { 22, "Passport" },
            { 23, "Custodial Key" },
            { 24, "Suitcase" },
            { 25, "CodMaster 2000\05" },
            { 26, "\"Prudish and Proud\"" },
            { 27, "\"Prudish and Proud\" Book Jacket" },
            { 28, "\"The Erotic Adventures of Hercules\"" },
            { 29, "\"Erotic\" Book In \"Prudish\" Jacket" },
            { 30, "Fire Hose" },
            { 31, "Silicone Lubricant" },
            { 32, "Deodorant Spray" },
            { 33, "Heat Lamp Bulb" },
            { 34, "Battery Powered Chase Lights" },
            { 35, "Remote Control" },
            { 36, "Horseshoe" },
            { 37, "Toilet Paper" },
            { 38, "Souvenir Dice" },
            { 39, "Shaved Dice" },
            { 40, "Legal Dice" },
            { 41, "Pot" },
            { 42, "Salt" },
            { 43, "Venezuelan Beaver Milk" },
            { 44, "Mold" },
            { 45, "Lime Juice" },
            { 46, "Venezuelan Beaver Cheese" },
            { 47, "Kumquats" },
            { 48, "Kumquat Quiche" },
            { 49, "Orgasmic Powder" },
            { 50, "Screwdriver" },
            { 51, "Jumper Wire" },
            { 52, "Carving Knife" },
            { 53, "Polyester Cloth" },
            { 54, "KZ Sexual Lubricant" },
            { 55, "Woman's Handkerchief" },
            { 56, "Treated Handkerchief" },
            { 57, "Bowling Ball" },
            { 58, "Life Insurance Policy" },
            { 59, "Stock Certificate" },
            { 60, "Throw" },
            { 61, "Open" },
            { 62, "Turn on" },
            { 63, "Unplug" },
            { 64, "Break" },
            { 65, "Bent Needle" },
            { 66, "Sex Fatigue" },
            { 67, "Drink" },
            { 68, "Name" },
            { 70, "Huh?" },
            { 71, "Smell" },
            { 72, "Wad o' Dough" },
            { 73, "Magazine Page" },
            { 74, "Quiche de Larry" },
            { 75, "The weather" },
            { 76, "Burp" },
            { 77, "Whiz" },
            { 78, "Stomp on" },
            { 79, "Play" },
            { 80, "Grope" },
            { 81, "Climb" },
            { 82, "Unlock" },
            { 83, "Undress" },
            { 84, "LoveMaster 2000" },
            { 85, "Sex" },
            { 86, "Goodbye" },
            { 87, "Blow" },
            { 88, "Suck" },
            { 89, "Tongue" },
            { 90, "Kiss" },
            { 91, "Nibble" },
            { 92, "Eat" },
            { 93, "Shit" },
            { 94, "Sit" },
            { 95, "Lie" },
            { 96, "Shipboard Competitions" },
            { 97, "Read" },
            { 98, "Lil' Hair Weave Kit" },
            { 99, "Peter the Purser" },
            { 102, "Job" },
            { 103, "Glasses" },
            { 104, "Dewey Decimal System" },
            { 105, "Good books" },
            { 106, "Check out" },
            { 107, "Pile of books" },
            { 108, "Go to bed" },
            { 109, "Best Dressed" },
            { 110, "Screw" },
            { 111, "Prove it" },
            { 112, "Other..." },
            { 113, "Date" },
            { 114, "Al Lowe" },
            { 115, "Ken Williams" },
            { 116, "Modeling" },
            { 117, "Turn off" },
            { 118, "Photographs" },
            { 119, "Sierra" },
            { 120, "Bowling" },
            { 121, "Photo ID" },
            { 122, "Passport" },
            { 123, "Climb in" },
            { 124, "Suitcase" },
            { 125, "CodMaster 2000" },
            { 126, "Your book" },
            { 127, "Anton Fokker" },
            { 128, "Your book" },
            { 129, "Shipboard life" },
            { 130, "Reading" },
            { 131, "Entertainment" },
            { 132, "Peggy" },
            { 133, "My cabin" },
            { 134, "Locker" },
            { 135, "Bend" },
            { 136, "Complain about room" },
            { 137, "Earplugs" },
            { 138, "\"Prudish And Proud\" Sans Jacket" },
            { 139, "Masturbate" },
            { 140, "Spotlights" },
            { 141, "How?" },
            { 142, "Where's Dildo?" },
            { 143, "Dream" },
            { 144, "Bowl" },
            { 145, "Lime juice" },
            { 146, "Operate" },
            { 147, "Kumquats" },
            { 148, "Heave" },
            { 149, "Your accent" },
            { 150, "Your name" },
            { 151, "Where's my cabin?" },
            { 152, "Move" },
            { 153, "Bolts of polyester" },
            { 154, "Stop" },
            { 155, "Ship's Map" },
            { 156, "Calvin Klone" },
            { 157, "Hot Tub" },
            { 158, "Insurance" },
            { 159, "Pet" },
            { 160, "Push" },
            { 162, "Excited" },
            { 163, "Free ticket" },
            { 164, "Ennui" },
            { 165, "But I won!" },
            { 166, "Life" },
            { 167, "Xqwzts" },
            { 168, "Xqwzts's hobby" },
            { 169, "Xqwzts's needs" },
            { 170, "Xqwzts's wants" },
            { 171, "Cabin boy" },
            { 173, "Combination" },
            { 174, "Peg leg" },
            { 176, "Clothing" },
            { 177, "Fokker" },
            { 179, "Drink" },
            { 180, "Anton's Fame" },
            { 181, "My place?" },
            { 182, "Annette Boning" },
            { 184, "My account" },
            { 185, "Telephone" },
            { 186, "Dial" },
            { 187, "Redial" },
            { 188, "Drew Baringmore" },
            { 189, "Unscrew" },
            { 190, "Buy pictures" },
            { 191, "Leisure suits" },
            { 192, "Distressed" },
            { 193, "Music" },
            { 194, "Show" },
            { 195, "Heat" },
            { 196, "Daughter" },
            { 197, "Big 'Uns" },
            { 198, "Women" },
            { 199, "Troubles" },
            { 200, "Bourbon" },
            { 201, "Remove jacket" },
            { 202, "Records" },
            { 203, "Cruise" },
            { 204, "Old Mr. Boning" },
            { 205, "Homosexuality" },
            { 206, "Flush" },
            { 207, "Get up" },
            { 208, "Sneeze" },
            { 209, "Breasts" },
            { 210, "Old man" },
            { 211, "Prank" },
            { 214, "Wipe" },
            { 215, "Codpieces" },
            { 217, "Over exposure" },
            { 218, "Swearing" },
            { 219, "Travel" },
            { 220, "Turn" },
            { 221, "Listen" },
            { 222, "Knock" },
            { 223, "Paper wads" },
            { 224, "Models" },
            { 225, "Ticket" },
            { 226, "An Idea" },
            { 227, "Spandex" },
            { 228, "Persons Magazine" },
            { 229, "Close" },
            { 230, "Look over" },
            { 231, "Unzip" },
            { 232, "Swap" },
            { 233, "Fashion" },
            { 234, "Milk" },
            { 235, "Joystick" },
            { 236, "Gigantic Erection" },
            { 237, "A Cocktail" },
            { 238, "Lamp" },
            { 239, "Sweatshops" },
            { 240, "Your collection" },
            { 241, "Fabrics" },
            { 242, "Where's home?" },
            { 243, "The Internet" },
            { 244, "Gambling" },
            { 245, "Strip Dice" },
            { 246, "Strategy" },
            { 247, "Pick up line" },
            { 249, "Call" },
            { 250, "You can't?" },
            { 251, "Unless" },
            { 252, "Lonely" },
            { 253, "Pick" },
            { 254, "Break room" },
        };

        // oInvHandler:initItems has the index of each of these before the object
        static string[] items =
        {
            "ioChaseLights",
            "ioLockpick",
            "ioBowlingBall",
            "ioKnife",
            "ioCodmaster",
            "ioCruiseTicket",
            "ioMasterKey",
            "ioDeodorant",
            "ioLewdPhoto",
            "ioEarPlugs",
            "ioEroticBook",
            "ioEroticAndProud",
            "ioFirehose",
            "ioHeatBulb",
            "ioHorseshoe",
            "ioJumperWire",
            "ioQuiche",
            "ioKumquat",
            "ioKZJelly",
            "ioLegalDice",
            "ioInsurance",
            "ioHairWeaveKit",
            "ioLimeJuice",
            "ioMagPage",
            "ioMap",
            "ioMold",
            "ioMucilage",
            "ioNeedle",
            "ioOrgasmPowder",
            "ioPassport",
            "ioPhotoID",
            "ioPolyester",
            "ioPot",
            "ioPrudeAndProud",
            "ioBookJacket",
            "ioNoCoverPrudeBk",
            "ioQuichePlus",
            "ioRemote",
            "ioSalt",
            "ioScrewdriver",
            "ioShavedDice",
            "ioLubricant",
            "ioSouvenirDice",
            "ioStickyPhoto",
            "ioStock",
            "ioSuitcase",
            "ioScorecard",
            "ioToiletPaper",
            "ioHankyLubed",
            "ioBeaverCheese",
            "ioBeaverMilk",
            "ioViceGrips",
            "ioMoney",
            "ioHanky",
            "ioKeyCard",
        };
    }
}
