using System;
using System.Collections.Generic;
using System.Linq;
using SCI.Annotators.Original;
using SCI.Language;

namespace SCI.Annotators
{
    class Qfg2Annotator : GameAnnotator
    {
        public override void Run()
        {
            RunEarly();
            GlobalRenamer.Run(Game, globals);
            ExportRenamer.Run(Game, exports);
            InventoryAnnotator.Run(Game, items);
            FlagAnnotator.Run(Game, flags);
            RunLate();

            SayAnnotator(Game, TextMessageFinder);

            QfgSkillAnnotator.Run(Game, 571, skills, new[] {
                Game.GetExport(2, 7), // TrySkill
                Game.GetExport(2, 8), // SkillUsed
            });
            Qfg12InventoryAnnotator.Run(Game, items); // after globals are renamed
            Qfg12GaitAnnotator.Run(Game); // after globals are renamed
            Qfg1EgaDeathAnnotator.Run(Game, TextMessageFinder);
            PrintSelectorAnnotator.Run(Game, Selectors, new[] { new PrintTextDef("EgoDead", 1) });
            GlobalEnumAnnotator.Run(Game, "gHeroType", characterClasses);
        }

        protected override Dictionary<int, Original.Script[]> GameHeaders { get { return Qfg2Symbols.Headers; } }

        static IReadOnlyCollection<PrintTextDef> printTextFunctions = new[]
        {
            new PrintTextDef("HighPrint"),
            new PrintTextDef("LowPrint"),
            new PrintTextDef("CenterPrint"),
            new PrintTextDef("TimePrint", 1),
            new PrintTextDef("djinniPrint"),
            new PrintTextDef("EgoDead", 1),
        };
        protected override IReadOnlyCollection<PrintTextDef> PrintTextFunctions { get { return printTextFunctions; } }

        static void SayAnnotator(Game game, TextMessageFinder messageFinder)
        {
            var sayName = game.GetExport(23, 0);

            foreach (var function in game.GetFunctions())
            {
                var sayListNodes = from n in function.Node
                                   where n.At(0).Text == sayName
                                   select n;

                foreach (var node in sayListNodes)
                {
                    // Say obj ## ##
                    // Say obj msgFile ##
                    // Say obj obj ## ##
                    for (int i = 2; i <= 3; i++)
                    {
                        if (node.At(i) is Integer &&
                            node.At(i + 1) is Integer)
                        {
                            var message = messageFinder.GetMessage(node.At(i).Number, node.At(i + 1).Number);
                            if (message != null)
                            {
                                node.At(0).Annotate(message.Text.QuoteMessageText());
                            }
                            break;
                        }
                        else if (node.At(i).Text == "msgFile" &&
                                 node.At(i + 1) is Integer)
                        {
                            int modNum = function.Object.GetIntegerProperty("msgFile");
                            if (modNum == int.MinValue)
                            {
                                var super = game.GetClasses().First(c => c.Name == function.Object.Super);
                                modNum = super.GetIntegerProperty("msgFile");
                                if (modNum == int.MinValue)
                                {
                                    break;
                                }
                            }
                            var message = messageFinder.GetMessage(modNum, node.At(i + 1).Number);
                            if (message != null)
                            {
                                node.At(0).Annotate(message.Text.QuoteMessageText());
                            }
                            break;
                        }
                    }
                }
            }
        }

        static Dictionary<int, string> globals = new Dictionary<int, string>
        {
            { 100, "gEgoGait" },
            { 101, "gDebugging" },
            { 102, "gCantTalk" },
            { 103, "gEgoX" },
            { 104, "gEgoY" },
            { 105, "gMachineSpeed" },
            { 106, "gCSound" },
            { 107, "gYesNoTimer" },
            { 108, "gLastRestTime" },
            { 109, "gLastRestDay" },
            { 110, "gDay" },
            { 111, "gClock" },
            { 112, "gTimeODay" },
            { 113, "gNight" },
            { 114, "gOldSysTime" },
            { 115, "gHeroType" },
            { 116, "gHowFast" },
            { 117, "gTransferRoom" },
            { 118, "gKeyDownHandler" },
            { 119, "gMouseDownHandler" },
            { 120, "gDirectionHandler" },
            { 121, "gCustomWindow" },
            { 122, "gEgoStopWalk" },
            { 123, "gLogFile" },
            { 124, "gRoomExitDir" },
            { 125, "gEgoLooper" },
            { 126, "gFastEgo" },
            { 127, "gNumColors" },
            { 128, "gNumVoices" },
            { 129, "gStamCounter" },
            { 130, "gHealCounter" },
            { 131, "gDrinksLeft" },
            { 132, "gFreeMeals" },
            { 133, "gLockPickBonus" },
            { 134, "gZapPower" },
            { 135, "gMonsterDazzle" },
            { 136, "gTargetAngles" },
            { 145, "gLostSleep" },
            { 146, "gMissedDaggers" },
            { 147, "gHitDaggers" },
            { 148, "gDaggerRoom" },
            { 149, "gSameColor" },
            { 150, "gChangeColor" },
            { 151, "gDftStatusCode" },
            { 152, "gCombatIconView" },
            { 153, "gStatusBarView" },
            { 154, "gCombatColor" },
            { 155, "gDeathMusic" },
            { 156, "gManaCounter" },
            { 157, "gXEgo" },
            { 158, "gYEgo" },
            { 159, "gWrestlingBet" },
            { 160, "gSwordBonus" },
            { 161, "gCantMove" },
            { 162, "gReversalTimer" },
            { 163, "gEgoBaseSetter" },
            { 164, "gMiscSound" },
            { 165, "gTimeScale" },
            { 166, "gLevHighY" },
            { 167, "gLevScript" },
            { 168, "gRopeHighY" },
            { 169, "gRopeScript" },
            { 170, "gRopeUses" },
            { 171, "gCIcon" },
            { 172, "gElementalState" },
            { 173, "gThirstCounter" },
            { 174, "gSpellChecker" },
            { 175, "gDefaultChecker" },
            { 176, "gAllChecker" },
            { 177, "gNoChecker" },
            { 178, "gNoWalkCursor" },
            { 179, "gNoTalkCursor" },
            { 180, "gSillyClowns" },
            { 181, "gPaladinPoints" },
            { 182, "gSpareSound" },
            { 183, "gDftHowFast" },
            { 184, "gTimeToEat" },
            { 185, "gNumScorpTails" },
            { 186, "gNumGhoulClaws" },
            { 187, "gOrigHeroType" },
            { 188, "gRoomThanks" },
            { 189, "gCurDayElemState" },
            { 190, "gHowMuchMemory" },
            { 191, "gPlazaDoorOpen" },
            { 192, "gRoomAsks" },
            { 193, "gEgoWalk" },
            { 194, "gOddTime" },
            { 251, "gMoneyDate" },
            { 252, "gBucks" },
            { 253, "gMonsterNum" },
            { 254, "gMonsterHealth" },
            { 255, "gShieldRoom" },
            { 256, "gOldScore" },
            { 257, "gInnLastHere" },
            { 258, "gInnLastAte" },
            { 259, "gEnter140" },
            { 260, "gGuildLastHere" },
            { 261, "gFortuneDay" },
            { 262, "gAstroVisits" },
            { 263, "gAlleyScript" },
            { 264, "gHarikVisits" },
            { 265, "gHarikDay" },
            { 266, "gUSE_ME_sits" },
            { 267, "gEnchLastHere" },
            { 268, "gEnter320" },
            { 269, "gMonsterMode" },
            { 270, "gMonsterRoom" },
            { 271, "gFakirVisits" },
            { 272, "gTightropeTried" },
            { 273, "gTightWinCount" },
            { 274, "gAzizaTemper" },
            { 275, "gLastTimeIn" },
            { 276, "gGriffinPOed" },
            { 277, "gNow" },
            { 278, "gCloseUpSubject" },
            { 279, "gCageLastHere" },
            { 280, "gBeastCare" },
            { 281, "gTashtariMsgNum" },
            { 282, "gSabaMsgNum" },
            { 283, "gLashamMsgNum" },
            { 284, "gWimpyHero" },
            { 285, "gCurDayMsg" },
            { 286, "gSloreeMsgNum" },
            { 287, "gToshurMsgNum" },
            { 288, "gKiramMsgNum" },
            { 289, "gMirakMsgNum" },
            { 290, "gDropObjRoom" },
            { 291, "gDropObjPosn" },
            { 292, "gAirPoints" },
            { 293, "gClumpsLeft" },
            { 294, "gFollowTime" },
            { 295, "gInnState" },
            { 296, "gFallCount" },
            { 297, "gArcadeLevel" },
            { 298, "gEarthElemHealth" },
            { 299, "gEarthElemStamina" },
            { 300, "gDesertRoom" },
            { 301, "gMagicLastHere" },
            { 302, "gMagicTrips" },
            { 303, "gPlazaLastHere" },
            { 304, "gBattleResult" },
            { 305, "gGateGuards" },
            { 306, "gGriffinHealth" },
            { 307, "gNAlichicaVisits" },
            { 308, "gDesertFunCtr" },
            { 309, "gSaurusRoom" },
            { 310, "gNumJackals" },
            { 311, "gJackalsKilled" },
            { 312, "gRasGuardLeft" },
            { 313, "gGuildCount1" },
            { 314, "gGuildCount2" },
            { 315, "gNoLevel" },
            { 316, "gHuhLevel" },
            { 317, "gEnchAlleyLast" },
            { 336, "gInvNum" },
            { 401, "gInvDropped" },
            { 466, "gInvWeight" },
            { 467, "gWicentime" },
            { 468, "gWidinar" },
            { 469, "gWifood" },
            { 470, "gWisword" },
            { 471, "gWidagger" },
            { 472, "gWileather" },
            { 473, "gWishield" },
            { 474, "gWipaper" },
            { 475, "gWirock" },
            { 476, "gWipick" },
            { 477, "gWikit" },
            { 478, "gWilicense" },
            { 479, "gWiincense" },
            { 480, "gWibeard" },
            { 481, "gWimail" },
            { 482, "gWirope" },
            { 483, "gWigold" },
            { 484, "gWiheal" },
            { 485, "gWimana" },
            { 486, "gWivigor" },
            { 487, "gWidispel" },
            { 488, "gWimap" },
            { 489, "gWicompass" },
            { 490, "gWifinesword" },
            { 491, "gWibellows" },
            { 492, "gWiflower" },
            { 493, "gWisapphpin" },
            { 494, "gWifeather" },
            { 495, "gWiscorp" },
            { 496, "gWighoul" },
            { 497, "gWisoulforge" },
            { 498, "gWidirt" },
            { 499, "gWilamp" },
            { 500, "gWibasket" },
            { 501, "gWiemptypot" },
            { 502, "gWifruit" },
            { 503, "gWiwaterskin" },
            { 504, "gWiclothbag" },
            { 505, "gWiburnpowder" },
            { 506, "gWieoftoken" },
            { 507, "gWivisa" },
            { 508, "gWioil" },
            { 509, "gWimagicwater" },
            { 510, "gWiring" },
            { 511, "gWiscarf" },
            { 512, "gWimirror" },
            { 513, "gWibird" },
            { 514, "gWicurepill" },
            { 515, "gWiclothes" },
            { 516, "gWisaurus" },
            { 517, "gWibagofsand" },
            { 518, "gWimagicearth" },
            { 519, "gWiteapot" },
            { 520, "gWiglasses" },
            { 521, "gWipurse" },
            { 522, "gWisilverdagger" },
            { 523, "gWibowl" },
            { 524, "gWinail" },
            { 531, "gOldStats" },
            { 570, "gEndStats" },
            { 571, "gEgoStats" },
            { 611, "gSkillTicks" },
            { 650, "gLastSkillTick" },
            { 651, "gSpCostOpen" },
            { 652, "gSpCostDetect" },
            { 653, "gSpCostTrigger" },
            { 654, "gSpCostDazzle" },
            { 655, "gSpCostZap" },
            { 656, "gSpCostCalm" },
            { 657, "gSpCostFlame" },
            { 658, "gSpCostFetch" },
            { 659, "gSpCostForce" },
            { 660, "gSpCostLevitate" },
            { 661, "gSpCostReversal" },
            { 670, "gSpellCostEnd" },
            { 671, "gUserName" },
            { 691, "gEndUserName" },
            { 692, "gLogName" },
            { 699, "gEndLogName" },
            { 700, "gGameFlags" },
            { 749, "gEndGameFlags" },
        };

        static Dictionary<int, string> characterClasses = new Dictionary<int, string>
        {
            { 0, "Fighter" },
            { 1, "Magic User" },
            { 2, "Thief" },
            { 3, "Paladin" }
        };

        static IReadOnlyDictionary<Tuple<int, int>, string> exports = new Dictionary<Tuple<int, int>, string>()
        {
        };

        // taken from enums in global.sh
        static string[] items =
        {
            "None", // there is no item 0 in this game
            "Centime",
            "Dinar",
            "Food",
            "Sword",
            "Dagger",
            "Leather",
            "Shield",
            "Paper",
            "Rock",
            "LockPick",
            "ThiefKit",
            "ThiefLicense",
            "Incense",
            "Beard",
            "ChainMail",
            "Rope",
            "Gold",
            "HealingPill",
            "ManaPill",
            "StaminaPill",
            "DispelPotion",
            "Map",
            "Compass",
            "FineSword",
            "Bellows",
            "Flowers",
            "SapphPin",
            "Feather",
            "ScorpionTail",
            "GhoulClaw",
            "Soulforge",
            "PotOfDirt",
            "BrassLamp",
            "Basket",
            "EmptyPot",
            "CompassionFruit",
            "Waterskin",
            "ClothBag",
            "BurningPowder",
            "EOFToken",
            "Visa",
            "Oil",
            "MagicWater",
            "Ring",
            "Scarf",
            "Mirror",
            "Bird",
            "PoisonCure",
            "SpareClothes",
            "Saurus",
            "BagOfSand",
            "MagicEarth",
            "Teapot",
            "Glasses",
            "Purse",
            "SilverDagger",
            "Bowl",
            "Nail",
        };

        static string[] skills =
        {
            "strength",
            "intelligence",
            "agility",
            "Vitality",
            "luck",
            "weapon-use",
            "parry",
            "dodge",
            "sneak",
            "pick locks",
            "throw",
            "climb",
            "magic use",
            "communication",
            "honor",
            "experience",
            "health",
            "stamina",
            "mana",
            "openSpell",
            "detectSpell",
            "triggerSpell",
            "dazzleSpell",
            "zapSpell",
            "calmSpell",
            "flameDartSpell",
            "fetchSpell",
            "forceBoltSpell",
            "levitateSpell",
            "invisibility",
            "reversalSpell"
        };

        static IReadOnlyDictionary<int, string> flags = new Dictionary<int, string>
        {
            { 0, "fImport" },
            { 1, "fSaveAllowed" },
            { 2, "fInMainGame" },
            { 3, "fThirsty" },
            { 4, "fHungry" },
            { 5, "fStarving" },
            { 6, "fOverloaded" },
            { 7, "fWornOut" },
            { 8, "fDemoing" },
            { 9, "fMoneyOnce" },
            { 10, "fMoneyTwice" },
            { 11, "fMoneySign" },
            { 12, "fMoneyMission" },
            { 13, "fMoneyDone" },
            { 14, "fTightropeWin" },
            { 15, "fTightrope" },
            { 16, "fShapeir" },
            { 17, "fWrestledOnce" },
            { 18, "fGoodFortune" },
            { 19, "fBadFortune" },
            { 20, "fSword" },
            { 21, "fWorthy" },
            { 22, "fBellows" },
            { 23, "fWrestlingWin" },
            { 24, "fWrestlingFun" },
            { 25, "fIssurMad" },
            { 26, "fWeaponRobbed" },
            { 27, "fCharImport" },
            { 28, "fTeleporting" },
            { 29, "fLishaTalkFire" },
            { 30, "fLishaTalkAir" },
            { 31, "fLishaTalkEarth" },
            { 32, "fLishaTalkCaravan" },
            { 33, "fGaveFeather" },
            { 34, "fGaveFruit" },
            { 35, "fMadeDispelPotion" },
            { 36, "fHeardDispelTalk" },
            { 37, "fGotBurnPowder" },
            { 38, "fBargainBet" },
            { 39, "fMoneyRumor" },
            { 40, "fAzizaOnce" },
            { 41, "fOfferedTea" },
            { 42, "fAlScurvaFreed" },
            { 43, "fDidPlant" },
            { 44, "fHeardPlant" },
            { 45, "fBoughtSaurus" },
            { 46, "fFromGateOnce" },
            { 47, "fFromDesertOnce" },
            { 48, "fIntoDesertOnce" },
            { 49, "fVisitedTiram" },
            { 50, "fVisitedSashanan" },
            { 51, "fPPWTalkFire" },
            { 52, "fPPWTalkAir" },
            { 53, "fPPWTalkWater" },
            { 54, "fPPWTalkEarth" },
            { 55, "fLampTaken" },
            { 56, "fRugRolled" },
            { 57, "fStoleTeapot" },
            { 58, "fStoleBowl" },
            { 59, "fStoleDagger" },
            { 60, "fHingesOiled" },
            { 61, "fHeardVoice" },
            { 62, "f210" },
            { 63, "fWITSponsor" },
            { 64, "fPassedPretest" },
            { 65, "fPassedTest" },
            { 66, "fWITName" },
            { 67, "fPassedAir" },
            { 68, "fPassedEarth" },
            { 69, "fPassedWater" },
            { 70, "fDervishCurse" },
            { 71, "fBabyMessage" },
            { 72, "fRakeeshSword" },
            { 73, "fMovedRock" },
            { 74, "fGriffinPOed" },
            { 75, "fDumbDownJoke" },
            { 76, "fDirtDown" },
            { 77, "fWaterDown" },
            { 78, "fHeroStory" },
            { 79, "fDirtStory" },
            { 80, "fPlantHug" },
            { 81, "fPlantName" },
            { 82, "fDesert" },
            { 83, "fToldMirak" },
            { 84, "fToldKiram" },
            { 85, "fBellowsGone" },
            { 86, "fReversal" },
            { 87, "fCastingSpell" },
            { 88, "fClimbingRope" },
            { 89, "fSaurusMessage" },
            { 90, "fLevitating" },
            { 91, "fUsingRope" },
            { 92, "fSpellCritical" },
            { 93, "fDervishMsg" },
            { 94, "fSharafFriend" },
            { 95, "fFalling" },
            { 96, "fTeleFromIblis" },
            { 97, "fUgarteBusted" },
            { 98, "fFerrariPOed" },
            { 99, "fThiefShown" },
            { 100, "fRaseir" },
            { 101, "fTomb" },
            { 102, "fDjinnSling" },
            { 103, "fBlownOff1" },
            { 104, "fBlownOff2" },
            { 105, "fBlownOff3" },
            { 106, "fBlownOff4" },
            { 107, "fWindShutOff" },
            { 108, "fVisitedAlichica" },
            { 109, "fSeenEarthElem" },
            { 110, "fHasDrink" },
            { 111, "fUgartePaid" },
            { 112, "fWaiting4Drink" },
            { 113, "fSpose2Sit" },
            { 114, "fAnvilMoved" },
            { 115, "fWeaponBarred" },
            { 116, "fLightOn" },
            { 117, "fPickingLock" },
            { 118, "f560msg" },
            { 119, "fPityMessage" },
            { 120, "fKeaponZoomed" },
            { 121, "fAntidote" },
            { 122, "fGotFruit" },
            { 123, "fTreeTurned" },
            { 124, "fTreeBloomed" },
            { 125, "fWearingXRay" },
            { 126, "fSaurusClose" },
            { 127, "f160" },
            { 128, "f140" },
            { 129, "f250" },
            { 130, "f199" },
            { 131, "f200" },
            { 132, "f240" },
            { 133, "fCantUseMap" },
            { 134, "f1stTimeRaseir" },
            { 135, "fRobbedPurse" },
            { 136, "fPurseInPlaza" },
            { 137, "fDyingOfThirst" },
            { 138, "fVisitedHaremGirl" },
            { 139, "fBookSigned" },
            { 140, "fEndGame" },
            { 141, "fKhaveenDead" },
            { 142, "fFollowingSlave" },
            { 143, "fFlyBy" },
            { 144, "fSeenHarpo" },
            { 145, "f1msgCaravan" },
            { 146, "f2msgCaravan" },
            { 147, "fBouncedBolt" },
            { 148, "fBoughtSapphPin" },
            { 149, "fReturningSaurus" },
            { 150, "fReturnedSaurus300" },
            { 151, "fReturnedSaurus320" },
            { 152, "f290" },
            { 153, "fCantBePaladin" },
            { 154, "fNotKilledEOF" },
            { 155, "fRodeSaurusOut" },
            { 156, "fBabaFrog" },
            { 157, "fUhuraMad" },
            { 158, "fRefusedReward" },
            { 159, "fPracticeFight" },
            { 160, "fFirstTime320" },
            { 161, "fSeenShow" },
            { 162, "fRanOutaMagic" },
            { 163, "fWITAgain" },
            { 164, "fOiledAnvil" },
            { 165, "fIssurMellow" },
            { 166, "f361" },
            { 167, "fMornMsg" },
            { 168, "fDervishDailyMsg" },
            { 169, "fDervishPeanutMsg" },
            { 170, "f100Message" },
            { 171, "fInvited2Sit" },
            { 172, "fLoseIfLeaves" },
            { 173, "fGuardWillDoIt" },
            { 174, "fSawDervish" },
            { 175, "fUhuraTired" },
            { 176, "fSeenPractice" },
            { 177, "fUhuraEnterMsg" },
            { 178, "fToldHarikOfFire" },
            { 179, "fToldHarikOfWater" },
            { 180, "fToldMagic250" },
            { 181, "fBurntTailSign" },
            { 182, "fAzizaSaurus" },
            { 183, "fWITWhyHere" },
            { 184, "fWhirlForBucks" },
            { 185, "fFreeFlowers" },
            { 186, "fSwordThanks" },
            { 187, "fFragment" },
        };
    }
}
