using System;
using System.Collections.Generic;
using System.Linq;

namespace SCI.Annotators
{
    class Sq6Annotator : GameAnnotator
    {
        public override void Run()
        {
            RunEarly();
            GlobalRenamer.Run(Game, globals);
            ExportRenamer.Run(Game, exports);
            // Use inventory script 15 to detect version
            var inventory = Game.GetScript(15);
            if (inventory.Instances.Any(i => i.Name == "Bjorn_Belt"))
            {
                // playable demo (early non-talkie or much later CD)
                VerbAnnotator.Run(Game, demoVerbs);
                InventoryAnnotator.Run(Game, demoItems);
            }
            else if (inventory.Instances.Any(i => i.Name == "Bedpan_Empty"))
            {
                // slideshow demo (has inventory items like bedpan that were cut)
                VerbAnnotator.Run(Game, slideshowDemoVerbs);
                InventoryAnnotator.Run(Game, slideshowDemoItems);
            }
            else
            {
                // full game
                VerbAnnotator.Run(Game, verbs);
                InventoryAnnotator.Run(Game, items);
            }

            RunLate();

            Sq6DeathAnnotator.Run(Game, MessageFinder);
            GlobalEnumAnnotator.Run(Game, 175, new Dictionary<int, string> {
                { 0, "Polysorbate" },
                { 1, "Delta Burksilon" },
                { 2, "Space" }
            });
        }

        static Dictionary<int, string> globals = new Dictionary<int, string>
        {
            {  100, "gDebugging" },
            {  119, "gComPostNextRoomNum" },
            {  120, "gAct" },
            {  148, "gShuttleRoomNum" },
            {  149, "gTalkedToDjurkwhad" },
            {  150, "gBuckazoidCount" },
            {  152, "gFileRoomRow" },
            {  153, "gNowServingNumber" },
            {  155, "gSidneyTalkCount" },
            {  158, "gEgoSpeed" },
            {  170, "gShuttleStatus" },
            {  171, "gLookedAtNigelFile" },
            {  172, "gCurrentMnM" },
            {  175, "gDeepshipLocation" },
            {  177, "gETTouchCount" },
            {  250, "gFlags" },
        };

        static IReadOnlyDictionary<Tuple<int, int>, string> exports = new Dictionary<Tuple<int, int>, string>()
        {
            { Tuple.Create(0, 1), "SetFlag" },
            { Tuple.Create(0, 2), "ClearFlag" },
            { Tuple.Create(0, 3), "IsFlag" },
            { Tuple.Create(0, 4), "Face" },
            { Tuple.Create(0, 7), "Fade" },
            // why did they make their own rng instead of calling kRandom?
            { Tuple.Create(0, 8), "RandomNumber" }, // constants appear in linear congruential generator code

            { Tuple.Create(666, 0), "EgoDead" },
        };

        static Dictionary<int, string> verbs = new Dictionary<int, string>
        {
            { 1, "Look" },
            { 2, "Talk" },
            { 3, "Walk" },
            { 4, "Do" },

            { 5, "Exit" },
            { 7, "ExitRight" },
            { 8, "ExitLeft" },
            { 9, "ExitUp" },
            { 10, "ExitDown" },

            { 6, "Datacorder" },
            { 12, "Donut" },
            { 13, "Empty_Tray" },
            { 14, "Trans_Signaler" },
            { 16, "Brandy" },
            { 22, "Duct_Tape" },
            { 27, "Crystal" },
            { 60, "Morphin" },
            { 61, "Morphing" },
            { 63, "Cheat_Sheet" },
            { 64, "Buckazoids" },
            { 65, "Full_Tray" },
            { 66, "Roger_Photos" },
            { 67, "Alien_ID" },
            { 68, "Roger_ID" },
            { 69, "Coin" },
            { 70, "Whisk_Broom" },
            { 71, "Hotel_Keycard" },
            { 72, "Hookah_Hose" },
            { 73, "Hookah_Connected" },
            { 74, "Dead_Fish" },
            { 75, "dummy1" },
            { 76, "Ch_Label" },
            { 77, "Burlesque_Moddie_4" },
            { 78, "dummy2" },
            { 79, "dummy3" },
            { 80, "Burlesque_Moddie_1" },
            { 81, "Churlish_Moddie_1" },
            { 82, "dummy4" },
            { 83, "dummy5" },
            { 84, "dummy6" },
            { 85, "Wall_Hanging" },
            { 86, "Hand_Cuffs" },
            { 87, "Keyring" },
            { 88, "Nail" },
            { 89, "Holozine" },
            { 90, "Belt_Da_Pga" },
            { 91, "Belt_Da" },
            { 92, "Belt_Pga" },
            { 93, "Actuator" },
            { 94, "Pga_Hair" },
            { 95, "Pga" },
            { 96, "Donut_Morph" },
            { 97, "Melon" },
            { 98, "Baguettes" },
            { 99, "Tubers" },
            { 100, "Rack_Of_Orat" },
            { 101, "Bobbit_Kabobs" },
            { 102, "Yoda_Ears" },
            { 103, "Gragh" },
            { 104, "Wad_Of_Hair" },
            { 105, "Data_Cart" },
            { 106, "Eulogy" },
            { 107, "Sidney_Arm" },
            { 108, "Sidney_Eye" },
            { 109, "Alarm_Key" },
            { 110, "Jumper_Cables" },
            { 111, "Windshield_Sign" },
            { 112, "Elmo_Gluzall" },
            { 113, "Eva_Suit" },
            { 114, "Eva_Helmet" },
            { 115, "Eva_Full" },
            { 116, "Recall_Notice" },
            { 117, "First_Photo" },
            { 118, "Second_Photo" },
            { 119, "First_Negative" },
            { 120, "Second_Negative" },
            { 121, "Hand_Pump" },
            { 122, "Callahan_Moddie" },
            { 128, "Cyber_Jack" },
            { 130, "Subroutine_Card" },
            { 131, "Rag" },
            { 132, "Screwdriver" },
            { 133, "Number_3_Cord" },
            { 134, "Silver_Chunk" },
            { 135, "Finger_Nail" },
            { 136, "Alveoli" },
            { 137, "Separated_Caps" },
            { 138, "Attach_Caps" },
            { 139, "Gallstone" },
            { 140, "Paperclip" },
            { 141, "M_M" },
            { 142, "Staple" },
            { 143, "Celery" },
            { 144, "Time_Pills" },
            { 145, "Grappling_Hook" },
            { 146, "Pinfeather" },
            { 147, "Nerve_Fibers" },
            { 148, "Magnet" },
            { 149, "Crap_O_Matic" },
            { 151, "Crystal_With_Glue" },
            { 154, "Pipe" },
            { 156, "Whisk_Broom_Full" },
            { 157, "First_Positive" },
            { 158, "Second_Positive" },
            { 159, "Pump_With_Hose" },
            { 160, "Board" },
            { 161, "Incriminating_Printouts" },
            { 162, "Belleaux_s_Record_Printout" },
            { 163, "Nigel_s_Record_Printout" },
            { 164, "Project_Immortality_Record_Printout" },
            { 165, "Sharpei_s_Record_Printout" },
            { 166, "Stellar_s_Record_Printout" },

            // of FileRecord of SQInvItem
            { 123, "Sape_Record" },
            { 124, "Nigel_Record" },
            { 125, "Project_Record" },
            { 126, "Beleaux_Record" },
            { 127, "Icky_Record" },
        };

        static string[] items =
        {
            "Actuator",
            "Alarm_Key",
            "Alien_ID",
            "Alveoli",
            "Attach_Caps",
            "Baguettes",
            "Beleaux_Record",
            "Belt_Da",
            "Belt_Da_Pga",
            "Belt_Pga",
            "Board",
            "Bobbit_Kabobs",
            "Brandy",
            "Buckazoids",
            "Burlesque_Moddie_1",
            "Burlesque_Moddie_4",
            "Callahan_Moddie",
            "Celery",
            "Cheat_Sheet",
            "Ch_Label",
            "Churlish_Moddie_1",
            "Coin",
            "Crap_O_Matic",
            "Crystal",
            "Crystal_With_Glue",
            "Cyber_Jack",
            "Data_Cart",
            "Datacorder",
            "Dead_Fish",
            "Dead_Fish2",
            "Dead_Fish3",
            "Donut",
            "Donut_Morph",
            "Duct_Tape",
            "dummy1",
            "dummy2",
            "dummy3",
            "dummy4",
            "dummy5",
            "dummy6",
            "Elmo_Gluzall",
            "Eulogy",
            "Eva_Full",
            "Eva_Full_Both",
            "Eva_Full_Enz",
            "Eva_Helmet",
            "Eva_Suit",
            "Finger_Nail",
            "First_Negative",
            "First_Photo",
            "First_Positive",
            "Gallstone",
            "Gragh",
            "Hand_Cuffs",
            "Hand_Pump",
            "Holozine",
            "Grappling_Hook",
            "Hookah_Connected",
            "Hookah_Hose",
            "Hotel_Keycard",
            "Empty_Tray",
            "Full_Tray",
            "Icky_Record",
            "Jumper_Cables",
            "Keyring",
            "M_M",
            "M_M_Green",
            "M_M_Yellow",
            "Magnet",
            "Melon",
            "Morphin",
            "Morphing",
            "Nail",
            "Nerve_Fibers",
            "Nigel_Record",
            "Number_3_Cord",
            "Paperclip",
            "Pga",
            "Pga_Hair",
            "Pinfeather",
            "Pipe",
            "Belleaux_s_Record_Printout",
            "Nigel_s_Record_Printout",
            "Project_Immortality_Record_Printout",
            "Sharpei_s_Record_Printout",
            "Stellar_s_Record_Printout",
            "Incriminating_Printouts",
            "Project_Record",
            "Pump_With_Hose",
            "Rack_Of_Orat",
            "Rag",
            "Recall_Notice",
            "Roger_ID",
            "Roger_Photos",
            "Sape_Record",
            "Screwdriver",
            "Second_Negative",
            "Second_Photo",
            "Second_Positive",
            "Separated_Caps",
            "Sidney_Arm",
            "Sidney_Eye",
            "Silver_Chunk",
            "Subroutine_Card",
            "Staple",
            "Time_Pills",
            "Trans_Signaler",
            "Tubers",
            "Wad_Of_Hair",
            "Wall_Hanging",
            "Whisk_Broom",
            "Whisk_Broom_Full",
            "Windshield_Sign",
            "Yoda_Ears",
        };

        static Dictionary<int, string> demoVerbs = new Dictionary<int, string>
        {
            { 1, "Look" },
            { 2, "Talk" },
            { 3, "Walk" },
            { 4, "Do" },

            { 5, "Exit" },
            { 7, "ExitRight" },
            { 8, "ExitLeft" },
            { 9, "ExitUp" },
            { 10, "ExitDown" },

            { 18, "Bjorn_Belt" },
            { 19, "Bjorn_Chow" },
            { 20, "Broken_Clap_Master" },
            { 21, "Fixed_Clap_Master" },
            { 22, "Duct_Tape" },
            { 23, "Pin" },
            { 24, "Pliers" },
            { 25, "Wrapped_Pliers" },
        };

        static string[] demoItems =
        {
            "Bjorn_Belt",
            "Bjorn_Chow",
            "Broken_Clap_Master",
            "Fixed_Clap_Master",
            "Duct_Tape",
            "Pin",
            "Pliers",
            "Wrapped_Pliers",
        };

        static Dictionary<int, string> slideshowDemoVerbs = new Dictionary<int, string>
        {
            { 1, "Look" },
            { 2, "Talk" },
            { 3, "Walk" },
            { 4, "Do" },

            { 5, "Exit" },
            { 7, "ExitRight" },
            { 8, "ExitLeft" },
            { 9, "ExitUp" },
            { 10, "ExitDown" },

            { 6, "Datacorder" },
            { 12, "Donut" },
            { 13, "Empty_Tray" },
            { 14, "Trans_Signaler" },
            { 16, "Brandy" },
            { 22, "Duct_Tape" },
            { 27, "Crystal" },
            { 60, "Morphin" },
            { 61, "Morphing" },
            { 63, "Cheat_Sheet" },
            { 64, "Buckazoids" },
            { 65, "Full_Tray" },
            { 66, "Roger_Photos" },
            { 67, "Alien_ID" },
            { 68, "Roger_ID" },
            { 69, "Coin" },
            { 70, "Whisk_Broom" },
            { 71, "Hotel_Keycard" },
            { 72, "Hookah_Hose" },
            { 73, "Hookah_Connected" },
            { 74, "Dead_Fish" },
            { 75, "Ish_Label" },
            { 76, "Ch_Label" },
            { 77, "Burlesque_Moddie_4" },
            { 78, "Burlesque_Moddie_3" },
            { 79, "Burlesque_Moddie_2" },
            { 80, "Burlesque_Moddie_1" },
            { 81, "Churlish_Moddie_1" },
            { 82, "Churlish_Moddie_2" },
            { 83, "Churlish_Moddie_3" },
            { 84, "Churlish_Moddie_4" },
            { 85, "Wall_Hanging" },
            { 86, "Hand_Cuffs" },
            { 87, "Keyring" },
            { 88, "Nail" },
            { 89, "Holozine" },
            { 90, "Belt_Da_Pga" },
            { 91, "Belt_Da" },
            { 92, "Belt_Pga" },
            { 93, "Actuator" },
            { 94, "Pga_Hair" },
            { 95, "Pga" },
            { 96, "Donut_Morph" },
            { 97, "Melon" },
            { 98, "Baguettes" },
            { 99, "Tubers" },
            { 100, "Rack_Of_Orat" },
            { 101, "Bobbit_Kabobs" },
            { 102, "Yoda_Ears" },
            { 103, "Gragh" },
            { 104, "Wad_Of_Hair" },
            { 105, "Data_Cart" },
            { 106, "Eulogy" },
            { 107, "Sidney_Arm" },
            { 108, "Sidney_Eye" },
            { 109, "Alarm_Key" },
            { 110, "Jumper_Cables" },
            { 111, "Windshield_Sign" },
            { 112, "Elmo_Gluzall" },
            { 113, "Eva_Suit" },
            { 114, "Eva_Helmet" },
            { 115, "Eva_Full" },
            { 116, "Recall_Notice" },
            { 117, "First_Photo" },
            { 118, "Second_Photo" },
            { 119, "First_Negative" },
            { 120, "Second_Negative" },
            { 121, "Hand_Pump" },
            { 122, "Callahan_Moddie" },
            { 123, "Sape_Record" },
            { 124, "Nigel_Record" },
            { 125, "Project_Record" },
            { 126, "Beleaux_Record" },
            { 127, "Icky_Record" },
            { 128, "Cyber_Jack" },
            { 129, "Bedpan_Roses" },
            { 130, "Bedpan_Empty" },
            { 131, "Rag" },
            { 132, "Magic_Marker" },
            { 133, "Number_3_Cord" },
            { 134, "Silver_Chunk" },
            { 135, "Finger_Nail" },
            { 136, "Alveoli" },
            { 137, "Separated_Caps" },
            { 138, "Attach_Caps" },
            { 139, "Gallstone" },
            { 140, "Paperclip" },
            { 141, "M_Ms" },
            { 142, "Staple" },
            { 143, "Celery" },
            { 144, "Time_Pills" },
            { 145, "Grappling_Hook" },
            { 146, "Pinfeather" },
            { 147, "Nerve_Fibers" },
            { 148, "Magnet" },
            { 149, "Crap_O_Matic" },
            { 150, "Spitcup_Full" },
            { 151, "Spitcup_Empty" },
        };

        static string[] slideshowDemoItems =
        {
            "Actuator",
            "Alarm_Key",
            "Alien_ID",
            "Alveoli",
            "Attach_Caps",
            "Baguettes",
            "Bedpan_Empty",
            "Bedpan_Roses",
            "Bedpan_Roses",
            "Beleaux_Record",
            "Belt_Da",
            "Belt_Da_Pga",
            "Belt_Pga",
            "Bobbit_Kabobs",
            "Brandy",
            "Buckazoids",
            "Burlesque_Moddie_1",
            "Burlesque_Moddie_2",
            "Burlesque_Moddie_3",
            "Burlesque_Moddie_4",
            "Callahan_Moddie",
            "Celery",
            "Cheat_Sheet",
            "Ch_Label",
            "Churlish_Moddie_1",
            "Churlish_Moddie_2",
            "Churlish_Moddie_3",
            "Churlish_Moddie_4",
            "Coin",
            "Crap_O_Matic",
            "Crystal",
            "Cyber_Jack",
            "Data_Cart",
            "Datacorder",
            "Dead_Fish",
            "Donut",
            "Donut_Morph",
            "Duct_Tape",
            "Elmo_Gluzall",
            "Eulogy",
            "Eva_Full",
            "Eva_Full",
            "Eva_Helmet",
            "Eva_Suit",
            "Finger_Nail",
            "First_Negative",
            "First_Photo",
            "Gallstone",
            "Gragh",
            "Hand_Cuffs",
            "Hand_Pump",
            "Holozine",
            "Grappling_Hook",
            "Hookah_Connected",
            "Hookah_Hose",
            "Hotel_Keycard",
            "Empty_Tray",
            "Full_Tray",
            "Icky_Record",
            "Ish_Label",
            "Jumper_Cables",
            "Keyring",
            "M_Ms",
            "Magic_Marker",
            "Magnet",
            "Melon",
            "Morphin",
            "Morphing",
            "Nail",
            "Nerve_Fibers",
            "Nigel_Record",
            "Number_3_Cord",
            "Paperclip",
            "Pga",
            "Pga_Hair",
            "Pinfeather",
            "Project_Record",
            "Rack_Of_Orat",
            "Rag",
            "Recall_Notice",
            "Roger_ID",
            "Roger_Photos",
            "Sape_Record",
            "Second_Negative",
            "Second_Photo",
            "Separated_Caps",
            "Sidney_Arm",
            "Sidney_Eye",
            "Silver_Chunk",
            "Spitcup_Empty",
            "Spitcup_Full",
            "Staple",
            "Time_Pills",
            "Trans_Signaler",
            "Tubers",
            "Wad_Of_Hair",
            "Wall_Hanging",
            "Whisk_Broom",
            "Windshield_Sign",
            "Yoda_Ears",
        };
    }
}
